# Generated by Django 6.0.3 on 2026-05-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_alter_user_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("student", "Студент"), ("teacher", "Преподаватель")],
                default="student",
                max_length=10,
                verbose_name="Роль",
            ),
        ),
    ]
