# Generated by Django 6.0.3 on 2026-05-07 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "teacher"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Закрепленный преподаватель",
            ),
        ),
    ]
