# Generated by Django 6.0.3 on 2026-05-23 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0006_studentgroup"),
        ("users", "0004_user_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="teacher",
        ),
        migrations.AddField(
            model_name="user",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="curriculum.studentgroup",
                verbose_name="Учебная группа",
            ),
        ),
    ]
