# Generated by Django 6.0.3 on 2026-06-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_teacher_user_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Студент"),
                    ("teacher", "Преподаватель"),
                    ("admin", "Администратор"),
                ],
                default="student",
                max_length=10,
                verbose_name="Роль",
            ),
        ),
    ]
