# Generated by Django 6.0.3 on 2026-03-30 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0001_initial"),
        ("solutions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews_given",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Преподаватель",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Студент",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="curriculum.task",
                verbose_name="Задание",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="submission",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="solutions.submission",
                verbose_name="Решение",
            ),
        ),
    ]
