# Generated by Django 6.0.3 on 2026-03-30 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solutions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name": "Рецензия", "verbose_name_plural": "Рецензии"},
        ),
        migrations.AlterModelOptions(
            name="submission",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Отправленная работа",
                "verbose_name_plural": "Отправленные работы",
            },
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="review",
            name="score",
            field=models.PositiveIntegerField(verbose_name="Полученный балл"),
        ),
        migrations.AlterField(
            model_name="review",
            name="submission",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="solutions.submission",
                verbose_name="Работа",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews_given",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Проверяющий преподаватель",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата последнего изменения"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="file",
            field=models.FileField(
                upload_to="submissions/%Y/%m/", verbose_name="Файл с решением"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает проверки"),
                    ("reviewing", "На проверке"),
                    ("completed", "Проверено"),
                    ("revision", "Нужна доработка"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус проверки",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата последнего изменения"
            ),
        ),
    ]
