# Generated by Django 6.0.3 on 2026-06-05 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("solutions", "0003_alter_review_options_alter_submission_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
    ]
