# Generated by Django 6.0.3 on 2026-03-30 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название модуля"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
            ],
            options={
                "verbose_name": "Учебный модуль",
                "verbose_name_plural": "Учебные модули",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Заголовок материала"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="materials/%Y/%m/", verbose_name="Файл материала"
                    ),
                ),
                (
                    "text_content",
                    models.TextField(blank=True, verbose_name="Текстовое содержание"),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="curriculum.module",
                        verbose_name="Модуль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Учебный материал",
                "verbose_name_plural": "Учебные материалы",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название задания"),
                ),
                ("description", models.TextField(verbose_name="Техническое задание")),
                ("deadline", models.DateTimeField(verbose_name="Срок сдачи")),
                (
                    "max_score",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Максимальный балл"
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="curriculum.module",
                        verbose_name="Модуль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задание",
                "verbose_name_plural": "Задания",
            },
        ),
    ]
