# Generated by Django 6.0.3 on 2026-03-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["deadline"],
                "verbose_name": "Задание",
                "verbose_name_plural": "Задания",
            },
        ),
        migrations.AlterField(
            model_name="material",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="material",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="materials/%Y/%m/",
                verbose_name="Файл материала",
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата последнего изменения"
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="module",
            name="description",
            field=models.TextField(verbose_name="Описание модуля"),
        ),
        migrations.AlterField(
            model_name="module",
            name="order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Порядок отображения"
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата последнего изменения"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(verbose_name="Крайний срок сдачи (дедлайн)"),
        ),
        migrations.AlterField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата последнего изменения"
            ),
        ),
    ]
