# Generated by Django 6.0.3 on 2026-05-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0002_alter_task_options_alter_material_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(verbose_name="Крайний срок сдачи"),
        ),
    ]
