# Generated by Django 6.0.3 on 2026-05-09 09:14

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0004_lecture_lectureimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                verbose_name="Содержание лекции"
            ),
        ),
    ]
