# Generated by Django 6.0.3 on 2026-05-23 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0006_studentgroup"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lecture",
            options={
                "ordering": ["title"],
                "verbose_name": "Лекция",
                "verbose_name_plural": "Лекции",
            },
        ),
        migrations.AlterModelOptions(
            name="module",
            options={
                "ordering": ["title"],
                "verbose_name": "Учебный модуль",
                "verbose_name_plural": "Учебные модули",
            },
        ),
        migrations.RemoveField(
            model_name="lecture",
            name="order",
        ),
        migrations.RemoveField(
            model_name="module",
            name="order",
        ),
    ]
