# Generated by Django 6.0.3 on 2026-06-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0007_alter_lecture_options_alter_module_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentgroup",
            name="title",
            field=models.CharField(
                max_length=7, unique=True, verbose_name="Название группы"
            ),
        ),
    ]
