# Generated by Django 6.0.3 on 2026-06-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0009_alter_material_options_alter_studentgroup_teacher"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="lecture",
            constraint=models.UniqueConstraint(
                fields=("module", "title"), name="unique_lecture_title_per_module"
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                fields=("module", "title"), name="unique_task_title_per_module"
            ),
        ),
    ]
